### ISSUE TITLE
Docker/Kubernetes Support

### ISSUE THREAD

**Issue by zquestz** [memberapp/server#3]
Definitely interested in running this, but would require at minimum a docker image to get this up and running in my infrastructure.

If this isn't already on the roadmap I would be happy to do the work. Basically making sure any settings can easily be set using ENV vars.

Let me know your thoughts.

**Comment by FreeTrade** [comment]
Thanks. I'm not very familiar with docker but I trust you know what you're doing and I'd welcome the contribution.

**Comment by FreeTrade** [comment]
Think this is done, thanks!
